import React,{useEffect,useMemo,useState}from'react'
import{createRoot}from'react-dom/client'
import{BarChart3,Box,ShoppingCart,Users,ReceiptText,LogOut,Save,Trash2,Edit3,Download,Printer,Shield,Database,Wallet}from'lucide-react'
import toast,{Toaster}from'react-hot-toast'
import'./style.css'

const API=import.meta.env.VITE_API_URL||'http://localhost:3000'
function api(path,opt={}){const token=localStorage.getItem('token');return fetch(API+path,{...opt,headers:{'Content-Type':'application/json',Authorization:token?'Bearer '+token:'',...(opt.headers||{})}}).then(async r=>{const text=await r.text();let data=text?JSON.parse(text):{};if(!r.ok)throw new Error(data.erro||'Erro');return data})}
function br(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function num(v){return String(v??'').replace(',','.')}

function Login({setUser}){const[email,setEmail]=useState('admin@admin.com'),[senha,setSenha]=useState('admin123');async function entrar(){try{const r=await api('/auth/login',{method:'POST',body:JSON.stringify({email,senha})});localStorage.setItem('token',r.token);setUser(r.user)}catch(e){toast.error(e.message)}}return <div className="login"><div className="login-card"><h1>ERP Fiscal Pro</h1><p>Entre para acessar o PDV</p><input value={email}onChange={e=>setEmail(e.target.value)}placeholder="email"/><input type="password"value={senha}onChange={e=>setSenha(e.target.value)}placeholder="senha"/><button onClick={entrar}>Entrar</button><small>Login inicial: admin@admin.com / admin123</small></div></div>}
function Layout({user,setUser}){const[page,setPage]=useState('dashboard');const menu=[['dashboard','Dashboard',BarChart3],['pdv','Caixa/PDV',ShoppingCart],['estoque','Estoque',Box],['clientes','Clientes',Users],['vendas','Vendas',ReceiptText],['caixa','Caixa diário',Wallet],['usuarios','Usuários',Shield],['backup','Backup',Database]];function sair(){localStorage.clear();setUser(null)}return <div className="app"><aside><h2>ERP<span>Fiscal</span></h2>{menu.map(([id,t,Icon])=><button key={id}className={page===id?'active':''}onClick={()=>setPage(id)}><Icon size={18}/>{t}</button>)}<button className="sair"onClick={sair}><LogOut size={18}/>Sair</button></aside><main>{page==='dashboard'&&<Dashboard/>}{page==='pdv'&&<PDV/>}{page==='estoque'&&<Estoque/>}{page==='clientes'&&<Clientes/>}{page==='vendas'&&<Vendas/>}{page==='caixa'&&<Caixa/>}{page==='usuarios'&&<Usuarios/>}{page==='backup'&&<Backup/>}</main></div>}
function Header({title}){return <><h1>{title}</h1><p className="sub">Gestão, estoque, PDV, XML, DANFE. Emissão fiscal real fica por último.</p></>}
function Dashboard(){const[d,setD]=useState(null);useEffect(()=>{api('/dashboard').then(setD).catch(e=>toast.error(e.message))},[]);const max=Math.max(...(d?.graficoVendas||[]).map(x=>Number(x.total)),1);return <><Header title="Dashboard"/><div className="cards"><Card t="Vendas hoje"v={br(d?.vendasHoje?.total)}/><Card t="Qtd. vendas"v={d?.vendasHoje?.qtd||0}/><Card t="Produtos"v={d?.produtos||0}/><Card t="Clientes"v={d?.clientes||0}/></div><section><h2>Gráfico de vendas</h2><div className="chart">{(d?.graficoVendas||[]).map(x=><div className="bar"key={x.dia}><span style={{height:20+Number(x.total)/max*120}}/><b>{x.dia}</b><em>{br(x.total)}</em></div>)}</div></section><section><h2>Estoque baixo</h2>{d?.estoqueBaixo?.length?d.estoqueBaixo.map(p=><div className="row"key={p.id}><b>{p.nome}</b><span>{p.estoque} {p.unidade}</span></div>):<p>Nenhum item crítico.</p>}</section></>}
function Card({t,v}){return <div className="card"><span>{t}</span><strong>{v}</strong></div>}
function Estoque(){const empty={nome:'',codigo_barras:'',preco:'',custo:'',estoque:'',estoque_min:'',ncm:'',cfop:'5102',unidade:'UN'};const[form,setForm]=useState(empty),[list,setList]=useState([]),[qv,setQv]=useState('');const load=()=>api('/produtos?q='+qv).then(setList).catch(e=>toast.error(e.message));useEffect(load,[qv]);function set(k,v){setForm({...form,[k]:v})}async function save(){try{const body={...form,preco:num(form.preco),custo:num(form.custo),estoque:num(form.estoque),estoque_min:num(form.estoque_min)};await api(form.id?'/produtos/'+form.id:'/produtos',{method:form.id?'PUT':'POST',body:JSON.stringify(body)});toast.success('Produto salvo');setForm(empty);load()}catch(e){toast.error(e.message)}}async function del(id){if(confirm('Excluir produto?')){await api('/produtos/'+id,{method:'DELETE'});load()}}return <><Header title="Estoque"/><section><h2>Novo produto</h2><div className="grid3">{['nome','codigo_barras','preco','custo','estoque','estoque_min','ncm','cfop','unidade'].map(k=><input key={k}placeholder={k}value={form[k]||''}onChange={e=>set(k,e.target.value)}/>)}</div><button onClick={save}><Save size={17}/>Salvar produto</button></section><section><div className="top"><h2>Produtos</h2><input placeholder="Buscar produto ou código"value={qv}onChange={e=>setQv(e.target.value)}/></div>{list.map(p=><div className="row"key={p.id}><b>{p.nome}<small>{p.codigo_barras}</small></b><span>{br(p.preco)}</span><span>{p.estoque} {p.unidade}</span><span>NCM {p.ncm}</span><button onClick={()=>setForm(p)}><Edit3 size={16}/></button><button className="danger"onClick={()=>del(p.id)}><Trash2 size={16}/></button></div>)}</section></>}
function Clientes(){const empty={nome:'',documento:'',email:'',telefone:'',endereco:''};const[form,setForm]=useState(empty),[list,setList]=useState([]);const load=()=>api('/clientes').then(setList);useEffect(load,[]);function set(k,v){setForm({...form,[k]:v})}async function save(){try{await api(form.id?'/clientes/'+form.id:'/clientes',{method:form.id?'PUT':'POST',body:JSON.stringify(form)});toast.success('Cliente salvo');setForm(empty);load()}catch(e){toast.error(e.message)}}async function del(id){if(confirm('Excluir cliente?')){await api('/clientes/'+id,{method:'DELETE'});load()}}return <><Header title="Clientes"/><section><h2>Cadastro</h2><div className="grid3">{Object.keys(empty).map(k=><input key={k}placeholder={k}value={form[k]||''}onChange={e=>set(k,e.target.value)}/>)}</div><button onClick={save}>Salvar cliente</button></section><section>{list.map(c=><div className="row"key={c.id}><b>{c.nome}<small>{c.documento}</small></b><span>{c.email}</span><span>{c.telefone}</span><button onClick={()=>setForm(c)}><Edit3 size={16}/></button><button className="danger"onClick={()=>del(c.id)}><Trash2 size={16}/></button></div>)}</section></>}
function PDV(){const[prod,setProd]=useState([]),[clientes,setClientes]=useState([]),[cart,setCart]=useState([]),[cliente,setCliente]=useState(''),[pag,setPag]=useState('PIX'),[busca,setBusca]=useState('');useEffect(()=>{api('/produtos').then(setProd);api('/clientes').then(setClientes)},[]);function add(p){setCart(c=>{const f=c.find(i=>i.id===p.id);return f?c.map(i=>i.id===p.id?{...i,qtd:i.qtd+1}:i):[...c,{...p,qtd:1}]})}function scan(e){if(e.key==='Enter'){const p=prod.find(x=>x.codigo_barras===busca||x.nome.toLowerCase().includes(busca.toLowerCase()));if(p)add(p);setBusca('')}}const total=cart.reduce((s,i)=>s+Number(i.preco)*i.qtd,0);async function fechar(){try{const v=await api('/vendas',{method:'POST',body:JSON.stringify({cliente_id:cliente||null,pagamento:pag,itens:cart.map(i=>({produto_id:i.id,quantidade:i.qtd}))})});toast.success('Venda fechada');setCart([]);window.open(API+`/vendas/${v.id}/danfe?token=${localStorage.getItem('token')}`,'_blank')}catch(e){toast.error(e.message)}}return <><Header title="Caixa/PDV"/><div className="pdv"><section><h2>Leitor código de barras</h2><input className="scan"placeholder="Bipe ou digite o código e Enter"value={busca}onKeyDown={scan}onChange={e=>setBusca(e.target.value)}autoFocus/><div className="products">{prod.map(p=><button key={p.id}onClick={()=>add(p)}><b>{p.nome}</b><span>{br(p.preco)}</span></button>)}</div></section><section><h2>Carrinho</h2><select value={cliente}onChange={e=>setCliente(e.target.value)}><option value="">Consumidor não identificado</option>{clientes.map(c=><option key={c.id}value={c.id}>{c.nome}</option>)}</select>{cart.map(i=><div className="row"key={i.id}><b>{i.qtd}x {i.nome}</b><span>{br(Number(i.preco)*i.qtd)}</span></div>)}<h1 className="total">{br(total)}</h1><select value={pag}onChange={e=>setPag(e.target.value)}><option>PIX</option><option>DINHEIRO</option><option>CARTÃO</option></select><button onClick={fechar}>Fechar venda</button><button onClick={()=>window.print()}><Printer size={17}/>Impressão térmica/browser</button></section></div></>}
function Vendas(){const[list,setList]=useState([]);useEffect(()=>{api('/vendas').then(setList)},[]);return <><Header title="Vendas"/><section>{list.map(v=><div className="row"key={v.id}><b>Venda {v.id}<small>{v.cliente||'Consumidor'} • {new Date(v.created_at).toLocaleString()}</small></b><span>{br(v.total)}</span><span>{v.pagamento}</span><a href={`${API}/vendas/${v.id}/danfe?token=${localStorage.getItem('token')}`}target="_blank">DANFE</a><a href={`${API}/vendas/${v.id}/xml?token=${localStorage.getItem('token')}`}target="_blank">XML</a></div>)}</section></>}
function Caixa(){const[d,setD]=useState(null),[form,setForm]=useState({tipo:'ENTRADA',descricao:'',valor:'',forma:'DINHEIRO'});const load=()=>api('/caixa').then(setD);useEffect(load,[]);async function add(){try{await api('/caixa/movimento',{method:'POST',body:JSON.stringify({...form,valor:num(form.valor)})});setForm({...form,descricao:'',valor:''});load()}catch(e){toast.error(e.message)}}return <><Header title="Caixa diário"/><section><h2>Movimento manual</h2><div className="grid3"><select value={form.tipo}onChange={e=>setForm({...form,tipo:e.target.value})}><option>ENTRADA</option><option>SAIDA</option></select><input placeholder="descrição"value={form.descricao}onChange={e=>setForm({...form,descricao:e.target.value})}/><input placeholder="valor"value={form.valor}onChange={e=>setForm({...form,valor:e.target.value})}/></div><button onClick={add}>Lançar</button></section><section>{d?.movimentos?.map(m=><div className="row"key={m.id}><b>{m.tipo}<small>{m.descricao}</small></b><span>{br(m.valor)}</span><span>{m.forma}</span></div>)}</section></>}
function Usuarios(){const empty={nome:'',email:'',senha:'',role:'caixa',ativo:true};const[form,setForm]=useState(empty),[list,setList]=useState([]);const load=()=>api('/usuarios').then(setList).catch(e=>toast.error(e.message));useEffect(load,[]);async function save(){try{await api(form.id?'/usuarios/'+form.id:'/usuarios',{method:form.id?'PUT':'POST',body:JSON.stringify(form)});toast.success('Usuário salvo');setForm(empty);load()}catch(e){toast.error(e.message)}}return <><Header title="Usuários e permissões"/><section><div className="grid3"><input placeholder="nome"value={form.nome}onChange={e=>setForm({...form,nome:e.target.value})}/><input placeholder="email"value={form.email}onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="senha"value={form.senha}onChange={e=>setForm({...form,senha:e.target.value})}/><select value={form.role}onChange={e=>setForm({...form,role:e.target.value})}><option>admin</option><option>gerente</option><option>caixa</option></select></div><button onClick={save}>Salvar usuário</button></section><section>{list.map(u=><div className="row"key={u.id}><b>{u.nome}<small>{u.email}</small></b><span>{u.role}</span><button onClick={()=>setForm({...u,senha:''})}>Editar</button></div>)}</section></>}
function Backup(){return <><Header title="Backup"/><section><h2>Backup manual</h2><p>Baixa um JSON com usuários, produtos, clientes, vendas, itens e caixa.</p><a className="btn" href={`${API}/backup?token=${localStorage.getItem('token')}`}target="_blank"><Download size={17}/>Baixar backup</a></section></>}
function App(){const[user,setUser]=useState(()=>localStorage.getItem('token')?{}:null);return <><Toaster/>{user?<Layout user={user}setUser={setUser}/>:<Login setUser={setUser}/>}</>}
createRoot(document.getElementById('root')).render(<App/> )
