import React, {useEffect, useMemo, useState} from 'react'
import {createRoot} from 'react-dom/client'
import axios from 'axios'
import {AreaChart, Area, ResponsiveContainer, XAxis, YAxis, Tooltip, CartesianGrid, BarChart, Bar} from 'recharts'
import {LayoutDashboard, ShoppingCart, Package, Users, ReceiptText, UserCog, Wallet, DatabaseBackup, Search, Pencil, Trash2, Plus, LogOut, Printer, FileCode, FileText, ShieldCheck} from 'lucide-react'
import './style.css'

const API = import.meta.env.VITE_API_URL || 'http://localhost:3000'
const money = v => Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const n = v => Number(String(v||0).replace(',','.'))||0

function App(){
  const [token,setToken]=useState(localStorage.getItem('token')||'')
  const [user,setUser]=useState(JSON.parse(localStorage.getItem('user')||'null'))
  const [page,setPage]=useState('dashboard')
  const [toast,setToast]=useState('')
  const api=useMemo(()=>axios.create({baseURL:API,headers:{Authorization:`Bearer ${token}`}}),[token])
  function ok(t){setToast(t);setTimeout(()=>setToast(''),2600)}
  function logout(){localStorage.clear();setToken('');setUser(null)}
  if(!token) return <Login setToken={setToken} setUser={setUser}/>
  const pages={dashboard:<Dashboard api={api}/>,pdv:<PDV api={api} ok={ok}/>,estoque:<Produtos api={api} ok={ok}/>,clientes:<Clientes api={api} ok={ok}/>,vendas:<Vendas api={api}/>,usuarios:<Usuarios api={api} ok={ok} user={user}/>,caixa:<Caixa api={api} ok={ok}/>,backup:<Backup api={api}/>}
  return <div className="app"><aside className="side"><div className="brand"><span>ERP</span>Fiscal <b>PRO</b></div><nav>{[
    ['dashboard',LayoutDashboard,'Dashboard'],['pdv',ShoppingCart,'Caixa/PDV'],['estoque',Package,'Estoque'],['clientes',Users,'Clientes'],['vendas',ReceiptText,'Vendas'],['caixa',Wallet,'Caixa diário'],['usuarios',UserCog,'Usuários'],['backup',DatabaseBackup,'Backup']
  ].map(([id,Icon,label])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon size={18}/>{label}</button>)}<button className="danger" onClick={logout}><LogOut size={18}/>Sair</button></nav><div className="me"><ShieldCheck size={16}/>{user?.nome}<small>{user?.perfil}</small></div></aside><main className="main">{toast&&<div className="toast">{toast}</div>}{pages[page]||pages.dashboard}</main></div>
}
function Login({setToken,setUser}){const [email,setEmail]=useState('admin@admin.com'),[senha,setSenha]=useState('admin123'),[erro,setErro]=useState(''); async function entrar(e){e.preventDefault();try{const r=await axios.post(`${API}/login`,{email,senha});localStorage.setItem('token',r.data.token);localStorage.setItem('user',JSON.stringify(r.data.usuario));setToken(r.data.token);setUser(r.data.usuario)}catch{setErro('Login inválido ou API fora do ar')}} return <div className="login"><form onSubmit={entrar} className="login-card"><div className="brand big"><span>ERP</span>Fiscal <b>PRO</b></div><p>Sistema premium de vendas, PDV e gestão fiscal.</p>{erro&&<div className="err">{erro}</div>}<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input value={senha} onChange={e=>setSenha(e.target.value)} type="password" placeholder="Senha"/><button>Entrar</button><small>Login inicial: admin@admin.com / admin123</small></form></div>}
function Header({title,desc}){return <header className="head"><h1>{title}</h1><p>{desc||'Gestão inteligente, visual premium e dados em tempo real.'}</p></header>}
function Dashboard({api}){const [d,setD]=useState({baixo:[],serie:[],fluxo:[]}); useEffect(()=>{api.get('/dashboard').then(r=>setD(r.data)).catch(console.error)},[]); return <><Header title="Dashboard"/><section className="cards"><Card t="Vendas hoje" v={money(d.vendasHoje)}/><Card t="Qtd. vendas" v={d.qtdVendas}/><Card t="Produtos" v={d.produtos}/><Card t="Clientes" v={d.clientes}/></section><section className="grid2"><div className="panel"><h2>Vendas dos últimos dias</h2><ResponsiveContainer width="100%" height={280}><AreaChart data={d.serie||[]}><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#fff" stopOpacity={0.35}/><stop offset="95%" stopColor="#fff" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="#222"/><XAxis dataKey="dia" stroke="#aaa"/><YAxis stroke="#aaa"/><Tooltip contentStyle={{background:'#080808',border:'1px solid #333'}}/><Area type="monotone" dataKey="total" stroke="#fff" fill="url(#g)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div><div className="panel"><h2>Fluxo de caixa hoje</h2><ResponsiveContainer width="100%" height={280}><BarChart data={d.fluxo||[]}><CartesianGrid strokeDasharray="3 3" stroke="#222"/><XAxis dataKey="tipo" stroke="#aaa"/><YAxis stroke="#aaa"/><Tooltip contentStyle={{background:'#080808',border:'1px solid #333'}}/><Bar dataKey="total" fill="#fff" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div></section><div className="panel"><h2>Estoque baixo</h2>{d.baixo?.length?d.baixo.map(p=><div className="row" key={p.id}><b>{p.nome}</b><span>{Number(p.estoque).toFixed(3)} {p.unidade}</span></div>):<p>Nenhum item crítico.</p>}</div></>}
function Card({t,v}){return <div className="card"><span>{t}</span><strong>{v}</strong></div>}
function Produtos({api,ok}){const empty={nome:'',codigo:'',preco:'',custo:'',estoque:'',estoque_min:'0',ncm:'',cfop:'5102',unidade:'UN'};const [list,setList]=useState([]),[form,setForm]=useState(empty),[edit,setEdit]=useState(null),[search,setSearch]=useState(''); const load=()=>api.get('/produtos',{params:{search}}).then(r=>setList(r.data)); useEffect(()=>{load()},[search]); async function save(e){e.preventDefault(); edit?await api.put(`/produtos/${edit}`,form):await api.post('/produtos',form); setForm(empty);setEdit(null);load();ok('Produto salvo')} async function del(id){if(confirm('Excluir produto?')){await api.delete(`/produtos/${id}`);load();ok('Produto excluído')}} return <Crud title="Estoque" search={search} setSearch={setSearch}><form className="premium-form" onSubmit={save}>{['nome','codigo','preco','custo','estoque','estoque_min','ncm','cfop','unidade'].map(k=><input key={k} placeholder={k} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/>) }<button><Plus size={18}/>{edit?'Atualizar':'Salvar produto'}</button></form><div className="table">{list.map(p=><div className="trow" key={p.id}><div><b>{p.nome}</b><small>{p.codigo}</small></div><span>{money(p.preco)}</span><span>{Number(p.estoque).toFixed(3)} {p.unidade}</span><span>NCM {p.ncm}</span><Actions edit={()=>{setEdit(p.id);setForm(p)}} del={()=>del(p.id)}/></div>)}</div></Crud>}
function Clientes({api,ok}){const empty={nome:'',documento:'',email:'',telefone:'',endereco:''};const [list,setList]=useState([]),[form,setForm]=useState(empty),[edit,setEdit]=useState(null),[search,setSearch]=useState(''); const load=()=>api.get('/clientes',{params:{search}}).then(r=>setList(r.data)); useEffect(()=>{load()},[search]); async function save(e){e.preventDefault(); edit?await api.put(`/clientes/${edit}`,form):await api.post('/clientes',form); setForm(empty);setEdit(null);load();ok('Cliente salvo')} async function del(id){if(confirm('Excluir cliente?')){await api.delete(`/clientes/${id}`);load();ok('Cliente excluído')}} return <Crud title="Clientes" search={search} setSearch={setSearch}><form className="premium-form" onSubmit={save}>{['nome','documento','email','telefone','endereco'].map(k=><input key={k} placeholder={k} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/>) }<button><Plus size={18}/>{edit?'Atualizar':'Salvar cliente'}</button></form><div className="table">{list.map(c=><div className="trow" key={c.id}><div><b>{c.nome}</b><small>{c.documento}</small></div><span>{c.email}</span><span>{c.telefone}</span><Actions edit={()=>{setEdit(c.id);setForm(c)}} del={()=>del(c.id)}/></div>)}</div></Crud>}
function Crud({title,children,search,setSearch}){return <><Header title={title}/><div className="toolbar"><div className="search"><Search size={18}/><input placeholder="Buscar" value={search} onChange={e=>setSearch(e.target.value)}/></div></div>{children}</>}
function Actions({edit,del}){return <div className="actions"><button onClick={edit}><Pencil size={16}/></button><button onClick={del}><Trash2 size={16}/></button></div>}
function PDV({api,ok}){const [prod,setProd]=useState([]),[cli,setCli]=useState([]),[cart,setCart]=useState([]),[cliente,setCliente]=useState(''),[pag,setPag]=useState('PIX'),[code,setCode]=useState(''); useEffect(()=>{api.get('/produtos').then(r=>setProd(r.data));api.get('/clientes').then(r=>setCli(r.data))},[]); const total=cart.reduce((s,i)=>s+i.preco*i.qtd,0); function add(p){setCart(c=>{const f=c.find(i=>i.id===p.id);return f?c.map(i=>i.id===p.id?{...i,qtd:i.qtd+1}:i):[...c,{...p,qtd:1,preco:Number(p.preco)}]})} function scan(e){e.preventDefault(); const p=prod.find(x=>x.codigo===code||String(x.id)===code); if(p)add(p); setCode('')} async function fechar(){try{await api.post('/vendas',{cliente_id:cliente||null,pagamento:pag,itens:cart.map(i=>({produto_id:i.id,quantidade:i.qtd}))}); printCupom(cart,total); setCart([]); ok('Venda fechada')}catch(e){alert(e.response?.data?.erro||'Erro')}} return <><Header title="Caixa/PDV"/><div className="pdv"><div className="panel"><h2>Leitor de código de barras</h2><form onSubmit={scan}><input className="scan" autoFocus placeholder="Bipe ou digite o código e Enter" value={code} onChange={e=>setCode(e.target.value)}/></form><div className="products">{prod.map(p=><button key={p.id} onClick={()=>add(p)}><b>{p.nome}</b><span>{money(p.preco)}</span><small>Estoque {Number(p.estoque).toFixed(3)}</small></button>)}</div></div><div className="panel cart"><h2>Carrinho</h2><select value={cliente} onChange={e=>setCliente(e.target.value)}><option value="">Consumidor não identificado</option>{cli.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select>{cart.map(i=><div className="row" key={i.id}><b>{i.qtd}x {i.nome}</b><span>{money(i.preco*i.qtd)}</span></div>)}<strong className="total">{money(total)}</strong><select value={pag} onChange={e=>setPag(e.target.value)}><option>PIX</option><option>Dinheiro</option><option>Cartão</option></select><button disabled={!cart.length} onClick={fechar}>Fechar venda</button><button className="ghost" onClick={()=>printCupom(cart,total)}><Printer size={16}/>Impressão térmica/browser</button></div></div></>}
function printCupom(cart,total){const w=open('','PRINT'); w.document.write(`<pre style="font-family:monospace;font-size:12px">ERP FISCAL PRO\n${new Date().toLocaleString('pt-BR')}\n----------------------\n${cart.map(i=>`${i.qtd}x ${i.nome} R$ ${(i.preco*i.qtd).toFixed(2)}`).join('\n')}\n----------------------\nTOTAL R$ ${total.toFixed(2)}</pre>`); w.print(); w.close()}
function Vendas({api}){const [v,setV]=useState([]); useEffect(()=>{api.get('/vendas').then(r=>setV(r.data))},[]); return <><Header title="Vendas"/><div className="table">{v.map(x=><div className="trow" key={x.id}><div><b>Venda #{x.id}</b><small>{new Date(x.criado_em).toLocaleString('pt-BR')}</small></div><span>{x.cliente||'Consumidor'}</span><span>{money(x.total)}</span><a target="_blank" href={`${API}/vendas/${x.id}/danfe?token=`}>DANFE</a><button onClick={()=>download(`${API}/vendas/${x.id}/xml`)}>XML</button></div>)}</div></>}
function Usuarios({api,ok,user}){const empty={nome:'',email:'',senha:'',perfil:'operador',ativo:true};const [list,setList]=useState([]),[form,setForm]=useState(empty),[edit,setEdit]=useState(null); const load=()=>api.get('/usuarios').then(r=>setList(r.data)).catch(e=>alert(e.response?.data?.erro||'Erro usuários')); useEffect(()=>{load()},[]); async function save(e){e.preventDefault(); edit?await api.put(`/usuarios/${edit}`,form):await api.post('/usuarios',form);setForm(empty);setEdit(null);load();ok('Usuário salvo')} return <><Header title="Usuários e permissões" desc="Controle de acesso para administradores e operadores."/><form className="premium-form" onSubmit={save}><input placeholder="nome" value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/><input placeholder="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="senha" value={form.senha} onChange={e=>setForm({...form,senha:e.target.value})}/><select value={form.perfil} onChange={e=>setForm({...form,perfil:e.target.value})}><option value="admin">admin</option><option value="operador">operador</option></select><button>Salvar usuário</button></form><div className="table">{list.map(u=><div className="trow" key={u.id}><div><b>{u.nome}</b><small>{u.email}</small></div><span>{u.perfil}</span><span>{u.ativo?'Ativo':'Inativo'}</span><Actions edit={()=>{setEdit(u.id);setForm({...u,senha:''})}} del={async()=>{await api.delete(`/usuarios/${u.id}`);load()}}/></div>)}</div></>}
function Caixa({api,ok}){const [list,setList]=useState([]),[form,setForm]=useState({tipo:'ENTRADA',descricao:'',valor:''}); const load=()=>api.get('/caixa').then(r=>setList(r.data)); useEffect(()=>{load()},[]); async function save(e){e.preventDefault(); await api.post('/caixa',form);setForm({tipo:'ENTRADA',descricao:'',valor:''});load();ok('Movimento salvo')} return <><Header title="Caixa diário"/><form className="premium-form" onSubmit={save}><select value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})}><option>ENTRADA</option><option>SAIDA</option></select><input placeholder="descrição" value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})}/><input placeholder="valor" value={form.valor} onChange={e=>setForm({...form,valor:e.target.value})}/><button>Adicionar</button></form><div className="table">{list.map(m=><div className="trow" key={m.id}><b>{m.tipo}</b><span>{m.descricao}</span><span>{money(m.valor)}</span><small>{new Date(m.criado_em).toLocaleString('pt-BR')}</small></div>)}</div></>}
function Backup({api}){return <><Header title="Backup"/><div className="panel center"><DatabaseBackup size={60}/><h2>Backup completo em JSON</h2><p>Baixe produtos, clientes, vendas e itens para segurança.</p><button onClick={()=>download(`${API}/backup`)}>Baixar backup</button></div></>}
function download(url){const token=localStorage.getItem('token'); fetch(url,{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.blob()).then(b=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='arquivo';a.click()})}

createRoot(document.getElementById('root')).render(<App />)
