import React, {useEffect,useMemo,useState} from 'react'
import { createRoot } from 'react-dom/client'
import { BarChart3, Boxes, LogOut, PackagePlus, Receipt, ShoppingCart, Users, Search, Printer, FileText, Download } from 'lucide-react'
import toast, { Toaster } from 'react-hot-toast'
import './style.css'

const API = import.meta.env.VITE_API_URL || 'http://localhost:3000'
const money = v => Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
function api(path, opt={}){ const token=localStorage.getItem('token'); return fetch(API+path,{...opt,headers:{'Content-Type':'application/json',Authorization: token?`Bearer ${token}`:'',...(opt.headers||{})}}).then(async r=>{const ct=r.headers.get('content-type')||''; if(!r.ok){let e={erro:'Erro'}; try{e=await r.json()}catch{} throw new Error(e.erro)} return ct.includes('application/json')?r.json():r.blob()}) }

function Login({on}){ const [email,setEmail]=useState('admin@admin.com'),[senha,setSenha]=useState('admin123')
 async function entrar(e){e.preventDefault(); try{const r=await api('/auth/login',{method:'POST',body:JSON.stringify({email,senha})}); localStorage.setItem('token',r.token); on(r.user)}catch(err){toast.error(err.message)}}
 return <div className="login"><form onSubmit={entrar} className="login-card"><div className="brand">ERP Fiscal Pro</div><p>Entre para acessar o PDV</p><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input value={senha} onChange={e=>setSenha(e.target.value)} placeholder="Senha" type="password"/><button>Entrar</button><small>Login inicial: admin@admin.com / admin123</small></form></div> }

function App(){ const [user,setUser]=useState(localStorage.getItem('token')?{nome:'Admin'}:null); if(!user) return <><Toaster/><Login on={setUser}/></>; return <ERP setUser={setUser}/> }
function ERP({setUser}){ const [tab,setTab]=useState('dashboard'); const nav=[['dashboard',BarChart3,'Dashboard'],['pdv',ShoppingCart,'Caixa/PDV'],['produtos',Boxes,'Estoque'],['clientes',Users,'Clientes'],['vendas',Receipt,'Vendas']]
 return <div className="app"><Toaster/><aside><div className="logo">ERP<span>Fiscal</span></div>{nav.map(([id,Icon,t])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><Icon size={18}/>{t}</button>)}<button className="exit" onClick={()=>{localStorage.clear();setUser(null)}}><LogOut size={18}/>Sair</button></aside><main><header><h1>{nav.find(n=>n[0]===tab)?.[2]}</h1><p>Gestão, estoque, PDV, XML e DANFE. Emissão fiscal real fica para a última etapa.</p></header>{tab==='dashboard'&&<Dashboard/>}{tab==='pdv'&&<PDV/>}{tab==='produtos'&&<Produtos/>}{tab==='clientes'&&<Clientes/>}{tab==='vendas'&&<Vendas/>}</main></div> }

function Dashboard(){ const [d,setD]=useState(null); useEffect(()=>{api('/dashboard').then(setD)},[]); if(!d) return <p>Carregando...</p>; return <><section className="cards"><Card t="Vendas hoje" v={money(d.vendasHoje.total)} /><Card t="Qtd. vendas" v={d.vendasHoje.qtd}/><Card t="Produtos" v={d.produtos}/><Card t="Clientes" v={d.clientes}/></section><section className="panel"><h2>Estoque baixo</h2>{d.estoqueBaixo.length?d.estoqueBaixo.map(p=><div className="row" key={p.id}><b>{p.nome}</b><span>{p.estoque} un</span></div>):<p>Nenhum item crítico.</p>}</section></> }
function Card({t,v}){return <div className="card"><span>{t}</span><strong>{v}</strong></div>}

function Produtos(){ const empty={nome:'',codigo_barras:'',preco:'',custo:'',estoque:'',estoque_min:'',ncm:'',cfop:'5102',unidade:'UN'}; const [f,setF]=useState(empty),[list,setList]=useState([]),[q,setQ]=useState(''); const load=()=>api('/produtos?q='+encodeURIComponent(q)).then(setList); useEffect(()=>{load()},[])
 async function salvar(e){e.preventDefault(); try{await api('/produtos',{method:'POST',body:JSON.stringify(f)}); setF(empty); load(); toast.success('Produto salvo')}catch(err){toast.error(err.message)}}
 return <><section className="panel"><h2><PackagePlus/> Novo produto</h2><form className="grid" onSubmit={salvar}>{Object.keys(empty).map(k=><input key={k} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})} placeholder={k.replace('_',' ')} required={k==='nome'||k==='preco'}/>) }<button>Salvar produto</button></form></section><section className="panel"><div className="toolbar"><h2>Produtos</h2><label><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Buscar produto ou código"/></label></div><table><tbody>{list.map(p=><tr key={p.id}><td><b>{p.nome}</b><small>{p.codigo_barras||'sem código'}</small></td><td>{money(p.preco)}</td><td>{p.estoque} {p.unidade}</td><td>NCM {p.ncm||'-'}</td></tr>)}</tbody></table></section></> }

function Clientes(){ const empty={nome:'',documento:'',email:'',telefone:'',endereco:''}; const [f,setF]=useState(empty),[list,setList]=useState([]); const load=()=>api('/clientes').then(setList); useEffect(()=>{load()},[]); async function salvar(e){e.preventDefault(); await api('/clientes',{method:'POST',body:JSON.stringify(f)}); setF(empty); load(); toast.success('Cliente salvo')}
 return <><section className="panel"><h2>Novo cliente</h2><form className="grid" onSubmit={salvar}>{Object.keys(empty).map(k=><input key={k} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})} placeholder={k} required={k==='nome'}/>) }<button>Salvar cliente</button></form></section><section className="panel"><h2>Clientes</h2>{list.map(c=><div className="row" key={c.id}><b>{c.nome}</b><span>{c.documento}</span></div>)}</section></> }

function PDV(){ const [prod,setProd]=useState([]),[clientes,setClientes]=useState([]),[cart,setCart]=useState([]),[cliente,setCliente]=useState(''),[busca,setBusca]=useState(''),[pagamento,setPagamento]=useState('DINHEIRO'); useEffect(()=>{api('/produtos').then(setProd);api('/clientes').then(setClientes)},[]); const total=useMemo(()=>cart.reduce((s,i)=>s+i.preco*i.qtd,0),[cart]); const add=p=>setCart(c=>{const ex=c.find(i=>i.id===p.id); return ex?c.map(i=>i.id===p.id?{...i,qtd:i.qtd+1}:i):[...c,{...p,qtd:1}]}); const scan=e=>{if(e.key==='Enter'){const p=prod.find(x=>x.codigo_barras===busca||String(x.id)===busca); p?add(p):toast.error('Produto não encontrado'); setBusca('')}}
 async function fechar(){ if(!cart.length) return toast.error('Carrinho vazio'); const venda=await api('/vendas',{method:'POST',body:JSON.stringify({cliente_id:cliente||null,pagamento,itens:cart.map(i=>({produto_id:i.id,quantidade:i.qtd}))})}); toast.success('Venda fechada'); printCupom(venda.id,cart,total); setCart([])}
 return <div className="pdv"><section className="panel"><h2>Leitor código de barras</h2><input className="big" autoFocus value={busca} onChange={e=>setBusca(e.target.value)} onKeyDown={scan} placeholder="Bipe o produto ou digite o código e Enter"/><div className="products">{prod.map(p=><button key={p.id} onClick={()=>add(p)}><b>{p.nome}</b><span>{money(p.preco)}</span></button>)}</div></section><section className="panel checkout"><h2>Carrinho</h2><select value={cliente} onChange={e=>setCliente(e.target.value)}><option value="">Consumidor não identificado</option>{clientes.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select>{cart.map(i=><div className="row" key={i.id}><b>{i.qtd}x {i.nome}</b><span>{money(i.qtd*i.preco)}</span></div>)}<h1>{money(total)}</h1><select value={pagamento} onChange={e=>setPagamento(e.target.value)}><option>DINHEIRO</option><option>PIX</option><option>CARTAO</option><option>BOLETO</option></select><button onClick={fechar}>Fechar venda</button><button className="ghost" onClick={()=>window.print()}><Printer size={16}/>Impressão térmica/browser</button></section></div> }
function printCupom(id,items,total){ const w=window.open('','_blank','width=360,height=600'); w.document.write(`<pre style="font-size:12px">ERP FISCAL PRO\nVenda ${id}\n--------------------\n${items.map(i=>`${i.qtd}x ${i.nome} R$ ${(i.qtd*i.preco).toFixed(2)}`).join('\n')}\n--------------------\nTOTAL R$ ${total.toFixed(2)}\n</pre><script>print()</script>`) }

function Vendas(){ const [list,setList]=useState([]); useEffect(()=>{api('/vendas').then(setList)},[]); async function baixar(id,tipo){ const blob=await api(`/vendas/${id}/${tipo}`); const url=URL.createObjectURL(blob); window.open(url,'_blank') }
 return <section className="panel"><h2>Vendas</h2><table><tbody>{list.map(v=><tr key={v.id}><td><b>#{v.id}</b><small>{new Date(v.created_at).toLocaleString('pt-BR')}</small></td><td>{v.cliente||'Consumidor'}</td><td>{money(v.total)}</td><td><button className="mini" onClick={()=>baixar(v.id,'danfe')}><FileText size={14}/>DANFE</button><button className="mini" onClick={()=>baixar(v.id,'xml')}><Download size={14}/>XML</button></td></tr>)}</tbody></table></section> }

createRoot(document.getElementById('root')).render(<App />)
